version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-2 --no-include-email)
      - REPOSITORY_URI=872089898249.dkr.ecr.us-east-2.amazonaws.com/node-web-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-web-app:latest .
      - docker tag node-web-app:latest 872089898249.dkr.ecr.us-east-2.amazonaws.com/node-web-app:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 872089898249.dkr.ecr.us-east-2.amazonaws.com/node-web-app:latest
      - printf '[{"name":"Node-Web-App","imageUri":"%s"}]' 872089898249.dkr.ecr.us-east-2.amazonaws.com/node-web-app:latest > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
  